### ISSUE TITLE
ownership change

### ISSUE THREAD

**Issue by dtenenba** [b-long/ServiceMonitoring#4]
Hi @b-long ,

Would you mind changing the ownership of this repo to the Bioconductor org?

If not we can just fork it. Thanks.

**Comment by b-long** [comment]
Hi @dtenenba , thanks for reaching out!  I'm actually using this for another project and it may be more helpful if I keep the root ownership.  I'm currently improving the project (starting with the install procedures) and would love to support various use cases.  Is there a particular feature you'd like added or bug you've discovered?  Absolutely happy to consider implementing them for you and of course I welcome pull requests.  👍

**Comment by b-long** [comment]
@dtenenba As mentioned, I have started to improve the install procedures.  Please take a look at https://github.com/b-long/ServiceMonitoring/pull/5 .  I do plan to update this repository, and would like to provide as much support to users as possible.  Any feedback would be greatly appreciated 😄 Are there features you'd like to see on the roadmap?

**Comment by dtenenba** [comment]
Sorry for the delay. That all sounds fine. Fyi I've moved on to a new position but am still helping out Bioconductor a bit.

**Comment by b-long** [comment]
No worries @dtenenba !  Really, I'm always happy to help Bioconductor .  I didn't realize you've left the project, but of course wish you all the best!  Keep in touch!
